# Generated by Django 5.1.4 on 2026-05-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_monthly_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry_failed', 'Retry Failed')], default='pending', max_length=15),
        ),
    ]
