# Generated by Django 5.1.4 on 2026-05-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_failedloginlog'),
        ('members', '0004_add_updated_at_to_member'),
    ]

    operations = [
    ]
